### ISSUE TITLE
Fatal error: Class 'K2HelperPermissions' not found....

### ISSUE THREAD

**Issue by Peter-2014** [joomlaworks/k2#206] opened 2014-09-30 17:06 UTC
Fatal error: Class 'K2HelperPermissions' not found in /.../administrator/components/com_k2/k2.php on line 39

this error came up aber installing
joomla 3.3.5

**Comment by tranduyhung** [comment] 2015-06-06 17:00
The same problem, the same error with K2 2.6.9 and Joomla 3.4.1 (fresh install, no third-party extensions).

Set error reporting to "Development" in Joomla's Global Configuration, go to site.com/administrator/index.php?option=com_k2, we get

	Notice: Use of undefined constant K2_JVERSION - assumed 'K2_JVERSION' in administrator/components/com_k2/k2.php on line 20
	Notice: Use of undefined constant DS - assumed 'DS' in administrator/components/com_k2/k2.php on line 38
	Notice: Use of undefined constant DS - assumed 'DS' in administrator/components/com_k2/k2.php on line 38
	Notice: Use of undefined constant DS - assumed 'DS' in administrator/components/com_k2/k2.php on line 38
	Notice: Use of undefined constant DS - assumed 'DS' in administrator/components/com_k2/k2.php on line 38
	Fatal error: Class 'K2HelperPermissions' not found in administrator/components/com_k2/k2.php on line 39

The same problem happens with K2 2.6.6, 2.6.7, 2.6.8.

However, if you use an older version of Joomla, everything is good.

To work around, I installed Joomla 3.2, installed K2 2.6.9, everything was successful, then update to Joomla 3.4.1. Now K2 works.

P/S: I just submit and hope the submitted info is helpful, I don't need help.

**Comment by kavadas** [comment] 2015-06-08 09:07
The error log indicates that the K2 system plugin is not enabled. Enable the system plugin and everything will work fine.

**Comment by web-seo** [comment] 2015-10-02 15:41
Kavadas, is not due on system plugin. The same error also on one of our clients sites with latest K2 and latest Joomla 3.4.4 - error was present immediately after install. Solution: open plugins page, search for k2 - find k2 search plugin and K2 smart search plugin and disable both plugins. After this K2 will work.

JoomlaWorks team must think about this issue in next version. This happened only on servers with activated FastCGI.

Cheers from Bulgaria.

**Comment by kavadas** [comment] 2015-10-05 10:07
@web-seo 

Can you provide more details on this? Just tested under Joomla! 3.4.4 with both Finder and Search plugins enabled and i see no issues.

**Comment by web-seo** [comment] 2015-12-17 07:06
I can't reproduce it, we use K2 only for testing purposes - to test compatibility with our Joomla extensions. I read in some russian webmaster forum that this happened only on servers with activated FastCGI. Is true - on server where we test ( http://androidappsdeveloper.net/ ) FastCGI is active.

**Comment by kavadas** [comment] 2016-02-02 13:31
Considered fixed with this https://github.com/joomlaworks/k2/commit/fd0464865deb2bb572a56192577876a01265e651 .

**Closed by kavadas** 2016-02-02 13:31 UTC

**Comment by web-seo** [comment] 2016-02-02 13:51
@kavadas, thank, will try it.

**Comment by orangeNapples** [comment] 2016-02-05 05:29
If you disable Cache Settings in (Global Configuration - System), the reinstall K2. Open anything in K2.. Then go back and Enable (Cache-Progressive) and set the Time to 60..
It should work..

**Comment by web-seo** [comment] 2016-02-05 07:13
?orangeNapples, Progressive cache in Joomla is for users only and give poor results with site speed performance, **conservative cache is the right setting**
